services:
  dujiao-api:
    image: dujiaonext/dujiao-next:latest
    container_name: dujiao-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - APP_DEBUG=true
      - DB_TYPE=sqlite
      - DB_DNS=/app/data/dujiao.db
      - JWT_SECRET=your-jwt-secret-change-in-production  # Please replace with a random key, e.g.: openssl rand -hex 32

  dujiao-user:
    image: dujiaonext/user:latest
    container_name: dujiao-user
    restart: always
    ports:
      - "8001:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

  dujiao-admin:
    image: dujiaonext/admin:latest
    container_name: dujiao-admin
    restart: always
    ports:
      - "8002:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000